### ISSUE TITLE
Share Material Shader Code -> off

### ISSUE THREAD

**Issue by Robert-K** [DRG-Modding/FSD-Template#1]
Share Material Shader Code in Packaging needs to be off to get custom material to show ingame. Why not include that here?
Also maybe include a note about UE4.25 not packaging skeletal meshes correctly (4.25+ needed for that) in the README.

**Comment by Buckminsterfullerene02** [comment]
Sorry for not seeing this earlier. The new template project has this turned on by default now. Regarding the UE4.25+ stuff, that is no longer required as UE4.27 has support for this.
